name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd client && npm ci
    
    - name: Create env file
      run: |
        echo "PORT=3000" >> .env
        echo "FIREBASE_ADMIN_KEY=${{ secrets.FIREBASE_ADMIN_KEY }}" >> .env

    - name: Type checking
      run: cd client && npm run type-check
      
    - name: Run linting
      run: cd client && npm run lint
    
    - name: Build project
      run: cd client && npm run build
    
    - name: Run frontend tests
      run: cd client && npm test

    - name: Run backend tests
      run: cd server && npm test